- enter.c
- enter.h
- main.c
- test/bst.t
Currently the umask from the caller's environment leaks into the spacetime and
can affect the resulting snapshot.
Rather than relying on users to explicitly set their umask, bst will set it
to 022 for all users.
> Add optional --umask flag for users to set umask on entry

- .gitignore
- Makefile
- bst-unpersist.1.scd
- bst.1.scd
- enter.c
- enter.h
- test/bst.t
- unpersist.c
These are a couple of commits that make the usage of re-entering and persisting namespace easier from an unprivileged user. We shouldn't have to use sudo to clear after a non-sudo operation, nor should we be using sudo to enter the spacetime of a running process that we own.
> Persisted namespace fixes and unprivileged unpersist

- enter.h
For some reason, this built fine on my ubuntu laptop as-is, but I was not able to build this under alpine without explicitly importing "sys/types.h".
With this patch, bst now builds successfully in an our barney.ci/bestie environment.
> Fix build under alpine

- Makefile
- capable.c
- capable.h
- enter.c
- main.c
- outer.c
- unpersist.c
This set of changes fix the last few gripes I've had with the capability code in bst.
First and foremost, libcap is dropped in favor of raw capget/capset code. Whatever the manpage for capget says, the matter of fact is that this new code is simpler, has 0 dynamic allocations, and just allows for the implementation of a better interface.
Second, I've realized that due to some misunderstanding of user namespaces on my end when I first wrote that code, the placement of the mount code (and almost everything after setresuid()) is just wrong. In this fixed version, we no longer need to give ourselves back capabilities after switching uids -- instead, the switch is done almost at the very end, where the only two remaining operations are chdir and execve. These are in fact the only two …
> Capability code cleanup & privilege model fixes

- .gitignore
- Makefile
- bst-init.1.scd
- bst.1.scd
- enter.c
- enter.h
- init.c
- main.c
- usage.txt
The first commit splits out bst-init into its own executable. This has a
bunch of interesting properties for bst:
First, it allows us to rewrite the process cmdline without doing
anything too crazy (*cough* PR_SET_MM_MAP), which helps tools
distinguish bst from its init process
Second, we don't need to explicitly mark the init as dumpable to let
inner processes with root privileges look at /proc/1/*.
Third, this lets us implement --init, which allows user to specify an
init process of their choosing, should the behaviour of *bst-init* not be
adapted to the situation they're in.
This supersedes #12.
The second commit is optional. I wanted to see if `bst --init=/some/init --share-pid` was even correct, but it turns out we can give it reasonable semantics. A somewhat interesting use-case is …
> Move bst-init to its own executable

- Makefile
- outer.c
- userns.c
- userns.h
bst would fail to create a proper id map if the id map of the parent
user namespace was already sliced up in multiple ranges. This is because
the kernel insists that ranges in an id map should be preserved, and
would refuse writes to the id map file with EPERM if this was not
respected.
For instance, if the current user namespace had this uid map:
0    0      1
1    1000   1000
1002 100000 64533
Then in order to map "0 0 65534", the following map would need to be
written:
0    0    1
1    1    1000
1002 1002 64533
This commit makes sure that the id map being written preserves these
slices by projecting the allowed id map of the owner of the new user
namespace onto the effective id map of the parent user namespace.
> userns: properly slice id maps

- init.c
If a debugger exits and leaves its child traced, then init inherits the
tracing of the process as well as becoming its parent.
Change our wait behaviour to detach from such children, and forward them
the signal that caused them to be stopped.
This stops us accumulating zombies if a debugger doesn't clean up on exit
> Deal with inheriting traced processes.

- mount.c
These add /dev/ptmx and /dev/tty to the fake devtmpfs mount.
> mount: add default /dev/ptmx and /dev/tty to bst_devtmpfs

- main.c
The "Program must be init of its pid namespace if no init is
specified" test would sometimes fail with a segmentation fault, and it
turns out the reason was that it would start searching backward for a
`/` at `opts.init` memory, wanting to stop no earlier than `opts.init`
itself, but it was starting one byte before, and so walked off into
strange places!
Check if `opts.init` is an empty string and skip this search if it is.
> misc: fix segfault with empty --init arg

- outer.c
It doesn't seem like it'll ever do a short write here, so `assert`
seemed like the best way to use the return value.
outer.c: In function ‘outer_helper_spawn’:
outer.c:294:2: warning: ignoring return value of ‘write’,
declared with attribute warn_unused_result [-Wunused-result]
294 |  write(pipefds_in[1], &ok, sizeof (ok));
|  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> misc: fix warning about ignored `write` return val

- outer.c
Not normalizing caused bst to complain that some IDs were not permissible
when the contents of /etc/sub{u,g}id where not sorted. This only
happened when trying to provide a custom mapping via --{u,g}id-map.
> userns: normalize subid file contents before intersecting the desired map

- enter.c
- path.c
- path.h
If the specified init program exists within the target root, we must not
open it before pivoting roots, as doing so is erroneous when the target
init is a symlink.
> init: do not open init program if within root

- enter.c
- mount.c
- path.c
- path.h
Previously, bst would give up trying to setup the fake devtmpfs mount if
the target was the host /dev. This was because setting up the fake
devtmpfs involved bind-mounting devices from the original /dev.
This commit makes this problem disappear by preparing said mount on /tmp
if we're trying to mount over the host /dev.
> mount: make bst_devtmpfs work on /dev

- enter.c
- tty.c
- tty.h
We were only getting the first signal since pselect unblocks all
signals after it is called instead of just restoring the mask.
Removed the use of pselect because it was redundant.  We were
already blocking the signals.
Also removed some of the hacks that were in place to work around
missing SIGCHLD.
Finally, added correct setting of the term window size on parent setup.
> pty: fix signal delivery

- mount.c
Also, make fake-devtmpfs more tolerant of devices that don't exist in
the host.
> Add fake-devtmpfs support for /dev/net/tun

- enter.c
- err.c
- errutil.h
- meson.build
- sig.c
- sig.h
- test/tty.t
- tty.c
- tty.h
These commits move away from select and sigwaitinfo, and collapses the two alternate wait code paths into one using epoll. It also fixes some minute issues with the way that we handle errors when the tty is in raw mode.
> Unify parent wait code using epoll

- capable.c
- capable.h
- enter.c
... and make the process dumpable. This allows unprivileged users to
debug and strace bst when it's past the initialization phase, without
the use of sudo.
> enter: drop all privileges in wait loop

- meson.build
Currently bst cannot build or run on platforms other than linux. Headers like
prctl.h, linux/capability.h etc are only available on Linux and not on other
platforms. Hence, the meson build process should check the target platform (the
platform for which the binary is being built) and bail out for non-supported
platforms. For example, when trying to build bst on my Mac's darwin platform, I
get the following descriptive error with this change:
Running test binary command: /Users/ani/workspace/bst/build/meson-private/sanitycheckc.exe
C compiler for the build machine: cc (clang 12.0.5 "Apple clang version 12.0.5 (clang-1205.0.22.11)")
C linker for the build machine: cc ld64 650.9
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: …
> build: restrict building bst for only linux platforms

- test/cram.sh
Document the '-p'/'--patch' option in the help string. 
Signed-off-by: Ani Sinha <ani@anisinha.ca>
> cram: add documentation for the -p option

- config.h.in
- meson.build
- mount.c
Historically, recursive read-only remounts of bind-mounts would only turn the top-level mount read-only. This is not a very good default, however, as it tend to surprise people.
Linux 5.12 has given us the means to do so via a new mount_setattr system call. This system call allows the caller to change properties of any given mount, and the combination of AT_RECURSIVE with MOUNT_ATTR_RDONLY has the previously described effect of going through all entries of the mount table recursively, and making them read-only.
> mount: properly recursively remount read-only

- meson.build
We have some security-sensitive code in here, so we might as well fortify by default.
> build: fortify sources by default when optimization level > 0

- enter.c
- outer.c
When all user-specified limits are non-critical (i.e., `--try-limit` instead of `--limit`), and we fail on basic subcgroup setup operations, we shouldn't treat this as a fatal error.
This change also removes 3 debug printf statements that cause tests to fail
> outer_helper_spawn: fail subcgroup creation silently when all limits are non-critical

- outer.c
When running in an environment with legacy cgroups, the cgroups-related parts of `outer_helper_spawn` aren't applicable. When a user invokes bst with `--try-limit`, the code needs to fail softly, as if no limit had been specified at all. We handle other cases of this earlier on the code, but we may (apparently) reach as far as burning the child pid into `cgroup.procs` before legacy cgroups balks, so we add another soft-failure for that case here.
> outer_helper_spawn: fail pid burn silently when all limits are non-critical

- enter.c
- outer.c
- sig.c
- sig.h
The way we've used PDEATHSIG so far was to call it in the child immediately after fork(). This is however inherently racy, because it is absolutely possible for the parent to get SIGKILL'ed after the fork, but before the child gets to call prctl.
This fixes the race by introducing a new function, sig_setpdeathsig.
The function takes the kill signal to pass to prctl PR_SET_PDEATHSIG, as well as the expected parent pid. The way to use this function is as follows:
pid_t ppid = getpid();
pid_t pid = fork();
if (pid == -1) {
err(1, "fork");
}
if (!pid) {
// in the child
sig_setpdeathsig(SIGKILL, ppid);
}
sig_setpdeathsig then takes care of calling prctl(PR_SET_PDEATHSIG, signo), and checks whether the current ppid is the same as the original ppid. If it isn't, it means the parent died and the …
> sig: make PDEATHSIG handling non-racy

- outer.c
Here's a little tree of processes:
```
main
|
+-(fork:outer_helper) writes uid/gid for child process
|                     then notifies main that it's done by
|                     writing to a socketpair
+-(fork:cgroup_helper) waits for all sibling processes to
|                     terminate then cleans up the cgroup
```
main waits for outer_helper to do some setup and then outer_helper notifies main that it's done by writing an `ok` to a socketpair. If outer_helper dies before it gets a chance to write the `ok` message, that should be fine - `main`'s end of the socketpair will close when all the references to the other side of the pair close. This normally happens as soon as outer_helper terminates because he as the only copy.
However, cgroup_helper also has a copy of that fd. It …
> cgroup_helper shan't hold socket for outer_helper process

- outer.c
The outer helper currently burns limits into the wrong place, as evidenced by this strace:
```
open("/proc/self/cgroup", O_RDONLY|O_LARGEFILE) = 4
mkdirat(4, "bst.2482939", 0777) = 0
openat(4, "bst.2482939", O_RDONLY|O_LARGEFILE|O_DIRECTORY) = 6
openat(4, "memory.oom.group", O_WRONLY|O_LARGEFILE) = 7
write(7, "1", 1) = 1
```
This change fixes it.
> outer helper: burn limits to the subcgroup, not the parent

- enter.c
- outer.c
- sig.c
- sig.h
79f40f6 (sig: make PDEATHSIG handling non-racy) introduced a failure mode that I hadn't forseen at the time; consider the following:
$ bst --pidfile=/tmp/pid sleep infinity &
$ bst --share all=/tmp/pid true
If you strace the second bst invocation, you'll see the following:
...
[pid 3475469] prctl(PR_SET_PDEATHSIG, SIGKILL) = 0
[pid 3475469] getppid() = 0
[pid 3475469] tgkill(1, 1, SIGKILL) = 0
Notice that getppid() returns 0 -- this happens because when entering an existing pid namespace, the parent of a non-init process (which exists outside of the namespace) gets replaced by 0. This sometimes confuses processes (especially shells), but is for the most part fairly innocent...
... except for the problem that 79f40f6 aimed to fix. The parent gets its own pid with getpid(), but that value …
> sig: check parent process liveness with fd read

- cgroup.c
- cgroup.h
- cgroup_native.c
- cgroup_systemd.c
- config.h.in
- enter.c
- enter.h
- generate
- main.c
- man/bst.1.scd
- meson.build
- outer.c
- outer.h
- usage.txt
The current cgroup implementation was in a very sad state, and was overall hard to use correctly, because it was trying to conciliate two very different system configurations: systemd-managed systems, and the contrary.
This PR makes bst limits more turnkey; that is, it now "just works" on the vast majority of systems without any additional configuration.
---
More specifically, this PR does two things: first, it refactors the current cgroup code into cgroup "drivers", and it provides two driver implementations: native, and systemd.
The native driver manages and cleans up cgroups directly, with no intermediary. It is appropriate to use in situations where nothing is owning the cgroups tree, like in most containers.
The systemd driver defers the management of the cgroup to systemd. It does …
> Revisit cgroup support and make it more turnkey

- cgroup.c
- cgroup.h
- cgroup_native.c
- cgroup_systemd.c
- main.c
- man/bst.1.scd
It is currently not possible to use bst with older versions of bst due to the older spacetime leaving the cgroup unconfigured. This means that /sys/fs/cgroup is unusable to the inner/newer bst, which in turn promptly fails.
> cgroup: fix various issues with compatibility with older bst spacetimes

- mount.c
This device is safe for unprivileged access, and is almost a must-have for running virtual machines with any reasonable performance.
> mount,dev: add support for /dev/kvm

- cgroup_systemd.c
343c4f1 ("cgroups,systemd: garbage-collect failed invocations") introduced an error in the dbus message by forgetting to add an additional key-value pair to the property list. This commit fixes this error.
> cgroup,systemd: fix typo in dbus payload structure

- compat.c
- compat.h
- enter.c
--close-fd would fail to work on some systems when entering spacetimes where /proc would not be mounted, because it would attempt to iterate over all file descriptors as listed in /proc/self/fd right before execve, and of course this cannot work when /proc isn't there.
This fixes the problem by doing the operation earlier, after the setup script has ran, but before pivoting roots; of course, we can't close the range outright, since we're likely to use some of these file descriptors, but we can instead set the CLOEXEC bit on them.
> fd: mark fds with CLOEXEC instead of closing them

- enter.c
- man/bst.1.scd
Some users of bst are still stuck on cgroups v1, and 588d370 ("cgroup,setup: set CGROUP_PATH in setup program with full path to current cgroup") broke the basic, non-cgroup use of bst.
This commit makes the failure to determine the current cgroup path non-fatal; the setup program has the responsibility to fail if it needs it.
> cgroup,setup: make CGROUP_PATH optional

- userns.c
The uid/gid map generation would incorrectly leave holes when the
current ID was greater than 2^16-1 and a combination of other factors.
The gist of it is that bst, assuming the current UID is 93119, and the
following /etc/subuid:
93119:100000:400000
... combined with the following system UID map:
0       1000    1
93119   93119   1
1       100000  93118
93120   193118  406882
... would need to attribute up to 400000 UIDs from the outer 100000 UID.
This attribution is done by mapping the current UID to inner UID 0, then
walking over the set of allotted subuids as defined in the /etc/subuid
file.
However, reading /etc/subuid would produce the following ID map:
0       93119   1
1       100000  400000
That is to say, bst would, upon reading /etc/subuid, insert an implicit
93119:93119:1 …
> userns: fix id map generating with holes under specific conditions

- outer.c
This commit eliminates all issues around pid reuse in the cgroup name.
Normally, the native cgroup cleaner (or systemd) would be responsible for garbage-collecting the cgroup of a previous bst invocation, but if we burn enough PIDs fast enough, it's also entirely possible for a new bst to start while the cleaner of an older invocation is busy cleaning up the old cgroup.
To fix the problem, we use a random 128-bit identifier instead of the pid in the name of the cgroup.
> cgroup: avoid using pid for cgroup name

- cgroup.c
- err.c
- errutil.h
The native cgroup cleaner used to report errors on stderr, but at that point the parent bst process might have already died, feeding the error message asynchronously on the pty, or worse, the pipe stderr is connected to might have already been closed.
To avoid losing precious debugging data, log any errors in the cgroup cleaner process to syslog instead.
> cgroup,cleaner: report errors in syslog

- err.c
- errutil.h
- main.c
Warnings are usually helpful to end-users but when bst is invoked by automations in a well controlled environment it is often preferable to only print fatal errors.
With this change, setting BST_VERBOSITY=0 will turn off non-fatal warnings.
> cli: Create BST_VERBOSITY to enable/disable warnings

- cgroup.c
- cgroup.h
- cgroup_native.c
Some callers of bst would send it a SIGKILL as soon as the underlying operation would get canceled. The problem is that it was possible to race the cgroup initialization code of the native driver, such that the SIGKILL would be received after mkdirat of the cgroup directory, but before the cgroup cleaner has any chance at starting.
This commit fixes this issue by reordering the operations. The cgroup cleaner is now started before mkdirat, and waits on a blocked pipe read until the parent process (which is the outer helper) dies. This ensures that the cleaner is started first and foremost, and that it waits until the cgroup has been initialized by the helper.
> cgroup,native: ensure we start the cleaner before creating cgroup

- cgroup.c
The old code used edge-triggered transitions for epoll_wait on the
cgroup.events file, which meant we were losing some events if we weren't
fast enough to process them. This, in turn, caused the unlucky cleaner
processes to hang on an epoll_wait, unable to clean up the unpopulated
cgroup.
With this commit, we now operate on level-triggered transitions, which
allows cleaners to do their jobs properly.
> cgroup,cleaner: wait on level-triggered transitions

- test/net.t
When listing interfaces using ip command, output depended on the system where the command was run. For example:
inet6 fe80::fced:deff:fead:beef/64 scope link
This line sometimes contains "tentative" at the end and sometimes not.
To avoid this problem json output from the ip command is used and parsed.
> Parse json output from ip command

- fd.c
- fd.h
- tty.c
This PR contains two changes:
The first one is a change in how we handle hangups from stdin; if the child pty is not in raw mode (or rather, is in non-canonical mode), and therefore isn't interpreting VEOF, then we won't send any. Instead, we now just hang up the terminal, which causes the session to die with a SIGHUP.
The second fixes a weirdity I noticed where we would not handle EOF properly, and commands like `bst --tty cat </dev/null` would not terminate.
> tty: stop spamming VEOF on raw terminals, and cleanly handle EOF

- .gitignore
- ns.c
Before this PR we would attempt to sort the namespaces to enter in order to decide what order to enter those namespaces. The sorting logic was somewhat complex and difficult to reason about.
With this change, we now just loop through the list of namespaces 3 times. During each loop, we unshare only a subset of namepaces (nonoverlapping subsets). This guaruntees that our unshares happen in roughly the order that they were declared in the namespaces list.
> Refactor order of unshare operations

- enter.c
- enter.h
- main.c
- ns.c
- ns.h
Before this commit, we used to construct shared namespace paths purely from string operations; that is, --share pid,mnt=/foo would be reconstructed as --share pid=/foo/pid --share mnt=/foo/mnt. The problem with this approach is that this doesn't work well with magic links to file descriptors in /proc.
Instead, we now open the directory path and use its file descriptor to open further nsfs files.
> enter: pass nsactions array rather than path array

- enter.c
- tty.c
When a session is hung up and a tty is allocated SIGHUP will be sent
to all processes in the session group.  Since we were ignoring SIGHUP
this led to bst processes hanging around.
Add signal handling for SIGHUP to close the tty master.  This will lead
to cleanup of the child session.
Fixes: 1047634
> tty: handle SIGHUP when allocating a tty

- main.c
- man/bst.1.scd
- tty.c
- tty.h
When ssh connections to buses are terminated bst is blocking while
draining the pty.  The signal handler does to run in this case and
the process hangs around until the bus is rebooted.
Added an option to control whether or not the pty is drained when
stdin is closed.  The b5c bst invocation will pass --tty=-drain.
> add an option to skip draining on tty close

- enter.c
As written we would always write a 64 byte pidfile with dozens of null terminator characters (or even garbage characters from non-zeroed memory). With this change we only write the decimal PID, a newline, and a single null terminator.
> Don't write trailing nulls to pidfile

- sec.c
The SECCOMP_IOCTL_NOTIF_RECV ioctl can fail with ENOENT if the target thread gets killed while it's blocked in a syscall the seccomp supervisor is handling, but before the supervisor manages to read any information about that system call.
This commit fixes this oversight by retrying on ENOENT.
> seccomp: handle ENOENT when receiving syscall

- outer.c
This most notably manifests with the native cgroup driver which waits for the parent to exit before performing a cleanup; the supervisor held onto a file descriptor that should have been closed in a non-seccomp scenario.
> outer,sec: close all fds before running supervisor loop
